import { Header } from "@/components/navigation/Header";
import { UserProvider } from "@/contexts/UserContext";
import { getUserFromToken } from "@/lib/auth";
import type { Metadata } from "next";
import { cookies } from 'next/headers';
import "../globals.css";
import { Footer } from "@/components/navigation/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const accessTokenCookie = (await cookies()).get("accessToken");
  const accessToken = accessTokenCookie ? accessTokenCookie.value : "";

  const user = await getUserFromToken(accessToken);

  return (
    <div className="flex flex-col min-h-screen">
    <UserProvider user={user}>
      <Header />
      <main className="flex-grow px-4 py-2">
        {children}
      </main>
      <Footer />
    </UserProvider>
    </div>
  );
}
